#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

# Check that the script is executed with sudo
if [ "$EUID" -ne 0 ]; then
  echo "Run with sudo"
  exit 1
fi

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Delete the old lines for localhost and facebook.com
sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

# Add new resolutions
echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts
